### ISSUE TITLE
Error: Your project requires a newer version of the Kotlin Gradle plugin

### ISSUE THREAD

**Issue by erperejildo** [jgrandchavin/game_services_firebase_auth#15]
I'm checking here but I have exactly the same version:
https://github.com/revoltgames/game_services_firebase_auth/blob/main/example/android/build.gradle#L2

Why is this necessary?

**Comment by jgrandchavin** [comment]
Hello 👋🏼

Sorry for the delay, should be ok now

**Comment by jgrandchavin** [comment]
It should be good now
